<p style="text-align:center">
    <a href="https://skills.network" target="_blank">
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/assets/logos/SN_web_lightmode.png" width="200" alt="Skills Network Logo">
    </a>
</p>

<h1 align=center><font size = 5>Assignment: SQL Notebook for Peer Assignment</font></h1>

Estimated time needed: **60** minutes.

## Introduction
Using this Python notebook you will:

1.  Understand the Spacex DataSet
2.  Load the dataset  into the corresponding table in a Db2 database
3.  Execute SQL queries to answer assignment questions

## Overview of the DataSet

SpaceX has gained worldwide attention for a series of historic milestones. 

It is the only private company ever to return a spacecraft from low-earth orbit, which it first accomplished in December 2010.
SpaceX advertises Falcon 9 rocket launches on its website with a cost of 62 million dollars wheras other providers cost upward of 165 million dollars each, much of the savings is because Space X can reuse the first stage. 


Therefore if we can determine if the first stage will land, we can determine the cost of a launch. 

This information can be used if an alternate company wants to bid against SpaceX for a rocket launch.

This dataset includes a record for each payload carried during a SpaceX mission into outer space.

### Download the datasets

This assignment requires you to load the spacex dataset.

In many cases the dataset to be analyzed is available as a .CSV (comma separated values) file, perhaps on the internet. Click on the link below to download and save the dataset (.CSV file):

 <a href="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_2/data/Spacex.csv" target="_blank">Spacex DataSet</a>

In [1]:
# Install once in your environment if needed:
# python -m pip install pandas
# This notebook uses Python's built-in sqlite3 module.

### Connect to the database

Let us first load the SQL extension and establish a connection with the database

In [2]:
# The notebook uses sqlite3 directly, so no IPython SQL extension is required.

In [3]:
import sqlite3
from pathlib import Path

import pandas as pd

con = sqlite3.connect(':memory:')
cur = con.cursor()

In [4]:
# The SQLite connection is created in the previous cell.

In [5]:
# Pandas was imported in the connection cell.

In [6]:
# Queries are executed with pandas.read_sql_query below.

In [7]:
dataset_candidates = [
    Path('Spacex.csv'),
    Path('../05-eda-sql/Spacex.csv'),
]
dataset_path = next((path for path in dataset_candidates if path.exists()), None)
if dataset_path is None:
    raise FileNotFoundError('Could not find the official Spacex.csv snapshot.')
df = pd.read_csv(dataset_path)
df.to_sql('SPACEXTBL', con, if_exists='replace', index=False)
print(f'Loaded {len(df)} rows from {dataset_path.resolve()}')
df.head()

Loaded 101 rows from K:\Uni Coding\ibm-data-science-capstone\05-eda-sql\Spacex.csv

,Date,Time (UTC),Booster_Version,Launch_Site,Payload,PAYLOAD_MASS__KG_,Orbit,Customer,Mission_Outcome,Landing_Outcome
0,2010-06-04,18:45:00,F9 v1.0 B0003,CCAFS LC-40,Dragon Spacecraft Qualification Unit,0,LEO,SpaceX,Success,Failure (parachute)
1,2010-12-08,15:43:00,F9 v1.0 B0004,CCAFS LC-40,"Dragon demo flight C1, two CubeSats, barrel of...",0,LEO (ISS),NASA (COTS) NRO,Success,Failure (parachute)
2,2012-05-22,7:44:00,F9 v1.0 B0005,CCAFS LC-40,Dragon demo flight C2,525,LEO (ISS),NASA (COTS),Success,No attempt
3,2012-10-08,0:35:00,F9 v1.0 B0006,CCAFS LC-40,SpaceX CRS-1,500,LEO (ISS),NASA (CRS),Success,No attempt
4,2013-03-01,15:10:00,F9 v1.0 B0007,CCAFS LC-40,SpaceX CRS-2,677,LEO (ISS),NASA (CRS),Success,No attempt

**Note:This below code is added to remove blank rows from table**

In [8]:
con.execute('DROP TABLE IF EXISTS SPACEXTABLE')
con.commit()

In [9]:
con.execute('CREATE TABLE SPACEXTABLE AS SELECT * FROM SPACEXTBL WHERE Date IS NOT NULL')
con.commit()
print(con.execute('SELECT COUNT(*) FROM SPACEXTABLE').fetchone()[0])

101

## Tasks

Now write and execute SQL queries to solve the assignment tasks.

**Note: If the column names are in mixed case enclose it in double quotes
   For Example "Landing_Outcome"**

### Task 1




##### Display the names of the unique launch sites  in the space mission

In [10]:
query = """SELECT DISTINCT Launch_Site FROM SPACEXTABLE ORDER BY Launch_Site;"""
result = pd.read_sql_query(query, con)
print('Unique launch sites')
display(result)

Unique launch sites

    Launch_Site
0   CCAFS LC-40
1  CCAFS SLC-40
2    KSC LC-39A
3   VAFB SLC-4E


### Task 2


#####  Display 5 records where launch sites begin with the string 'CCA'

In [11]:
query = """SELECT * FROM SPACEXTABLE WHERE Launch_Site LIKE 'CCA%' LIMIT 5;"""
result = pd.read_sql_query(query, con)
print('Five CCA launch-site records')
display(result)

Five CCA launch-site records

,Date,Time (UTC),Booster_Version,Launch_Site,Payload,PAYLOAD_MASS__KG_,Orbit,Customer,Mission_Outcome,Landing_Outcome
0,2010-06-04,18:45:00,F9 v1.0 B0003,CCAFS LC-40,Dragon Spacecraft Qualification Unit,0,LEO,SpaceX,Success,Failure (parachute)
1,2010-12-08,15:43:00,F9 v1.0 B0004,CCAFS LC-40,"Dragon demo flight C1, two CubeSats, barrel of...",0,LEO (ISS),NASA (COTS) NRO,Success,Failure (parachute)
2,2012-05-22,7:44:00,F9 v1.0 B0005,CCAFS LC-40,Dragon demo flight C2,525,LEO (ISS),NASA (COTS),Success,No attempt
3,2012-10-08,0:35:00,F9 v1.0 B0006,CCAFS LC-40,SpaceX CRS-1,500,LEO (ISS),NASA (CRS),Success,No attempt
4,2013-03-01,15:10:00,F9 v1.0 B0007,CCAFS LC-40,SpaceX CRS-2,677,LEO (ISS),NASA (CRS),Success,No attempt

### Task 3




##### Display the total payload mass carried by boosters launched by NASA (CRS)

In [12]:
query = """SELECT SUM(PAYLOAD_MASS__KG_) AS total_payload_mass_kg FROM SPACEXTABLE WHERE Customer LIKE '%NASA (CRS)%';"""
result = pd.read_sql_query(query, con)
print('Total NASA CRS payload mass')
display(result)

Total NASA CRS payload mass

   total_payload_mass_kg
0                  48213

### Task 4




##### Display average payload mass carried by booster version F9 v1.1

In [13]:
query = """SELECT AVG(PAYLOAD_MASS__KG_) AS average_payload_mass_kg FROM SPACEXTABLE WHERE Booster_Version LIKE 'F9 v1.1%';"""
result = pd.read_sql_query(query, con)
print('Average F9 v1.1 payload mass')
display(result)

Average F9 v1.1 payload mass

   average_payload_mass_kg
0              2534.666667

### Task 5

##### List the date when the first succesful landing outcome in ground pad was acheived.


_Hint:Use min function_

In [14]:
query = """SELECT MIN(Date) AS first_successful_ground_pad_date FROM SPACEXTABLE WHERE Landing_Outcome LIKE 'Success (ground pad)%';"""
result = pd.read_sql_query(query, con)
print('First successful ground-pad landing')
display(result)

First successful ground-pad landing

  first_successful_ground_pad_date
0                       2015-12-22

### Task 6

##### List the names of the boosters which have success in drone ship and have payload mass greater than 4000 but less than 6000

In [15]:
query = """SELECT Booster_Version, PAYLOAD_MASS__KG_, Landing_Outcome FROM SPACEXTABLE WHERE Landing_Outcome = 'Success (drone ship)' AND PAYLOAD_MASS__KG_ > 4000 AND PAYLOAD_MASS__KG_ < 6000 ORDER BY PAYLOAD_MASS__KG_;"""
result = pd.read_sql_query(query, con)
print('Successful drone-ship boosters in the requested mass range')
display(result)

Successful drone-ship boosters in the requested mass range

  Booster_Version  PAYLOAD_MASS__KG_       Landing_Outcome
0     F9 FT B1026               4600  Success (drone ship)
1     F9 FT B1022               4696  Success (drone ship)
2  F9 FT  B1031.2               5200  Success (drone ship)
3  F9 FT  B1021.2               5300  Success (drone ship)

### Task 7




##### List the total number of successful and failure mission outcomes

In [16]:
query = """SELECT Mission_Outcome, COUNT(*) AS mission_count FROM SPACEXTABLE GROUP BY Mission_Outcome ORDER BY mission_count DESC;"""
result = pd.read_sql_query(query, con)
print('Mission outcome counts')
display(result)

Mission outcome counts

                    Mission_Outcome  mission_count
0                           Success             98
1  Success (payload status unclear)              1
2                          Success               1
3               Failure (in flight)              1

### Task 8



##### List all the booster_versions that have carried the maximum payload mass, using a subquery with a suitable aggregate function.

In [17]:
query = """SELECT Booster_Version, PAYLOAD_MASS__KG_ FROM SPACEXTABLE WHERE PAYLOAD_MASS__KG_ = (SELECT MAX(PAYLOAD_MASS__KG_) FROM SPACEXTABLE);"""
result = pd.read_sql_query(query, con)
print('Booster versions carrying the maximum payload')
display(result)

Booster versions carrying the maximum payload

   Booster_Version  PAYLOAD_MASS__KG_
0    F9 B5 B1048.4              15600
1    F9 B5 B1049.4              15600
2    F9 B5 B1051.3              15600
3    F9 B5 B1056.4              15600
4    F9 B5 B1048.5              15600
5    F9 B5 B1051.4              15600
6    F9 B5 B1049.5              15600
7   F9 B5 B1060.2               15600
8   F9 B5 B1058.3               15600
9    F9 B5 B1051.6              15600
10   F9 B5 B1060.3              15600
11  F9 B5 B1049.7               15600

### Task 9


##### List the records which will display the month names, failure landing_outcomes in drone ship ,booster versions, launch_site for the months in year 2015.

**Note: SQLLite does not support monthnames. So you need to use  substr(Date, 6,2) as month to get the months and substr(Date,0,5)='2015' for year.**

In [18]:
query = """SELECT CASE substr(Date, 6, 2) WHEN '01' THEN 'January' WHEN '02' THEN 'February' WHEN '03' THEN 'March' WHEN '04' THEN 'April' WHEN '05' THEN 'May' WHEN '06' THEN 'June' WHEN '07' THEN 'July' WHEN '08' THEN 'August' WHEN '09' THEN 'September' WHEN '10' THEN 'October' WHEN '11' THEN 'November' WHEN '12' THEN 'December' END AS month, Landing_Outcome, Booster_Version, Launch_Site FROM SPACEXTABLE WHERE substr(Date, 1, 4) = '2015' AND Landing_Outcome = 'Failure (drone ship)' ORDER BY substr(Date, 6, 2);"""
result = pd.read_sql_query(query, con)
print('2015 drone-ship failures by month')
display(result)

2015 drone-ship failures by month

     month       Landing_Outcome Booster_Version  Launch_Site
0  January  Failure (drone ship)   F9 v1.1 B1012  CCAFS LC-40
1    April  Failure (drone ship)   F9 v1.1 B1015  CCAFS LC-40

### Task 10




##### Rank the count of landing outcomes (such as Failure (drone ship) or Success (ground pad)) between the date 2010-06-04 and 2017-03-20, in descending order.

In [19]:
query = """SELECT Landing_Outcome, COUNT(*) AS outcome_count FROM SPACEXTABLE WHERE Date BETWEEN '2010-06-04' AND '2017-03-20' GROUP BY Landing_Outcome ORDER BY outcome_count DESC;"""
result = pd.read_sql_query(query, con)
print('Landing-outcome counts between the requested dates')
display(result)

Landing-outcome counts between the requested dates

          Landing_Outcome  outcome_count
0              No attempt             10
1    Success (drone ship)              5
2    Failure (drone ship)              5
3    Success (ground pad)              3
4      Controlled (ocean)              3
5    Uncontrolled (ocean)              2
6     Failure (parachute)              2
7  Precluded (drone ship)              1

### Reference Links

* <a href ="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/Labs_Coursera_V5/labs/Lab%20-%20String%20Patterns%20-%20Sorting%20-%20Grouping/instructional-labs.md.html?origin=www.coursera.org">Hands-on Lab : String Patterns, Sorting and Grouping</a>  

*  <a  href="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/Labs_Coursera_V5/labs/Lab%20-%20Built-in%20functions%20/Hands-on_Lab__Built-in_Functions.md.html?origin=www.coursera.org">Hands-on Lab: Built-in functions</a>

*  <a  href="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/Labs_Coursera_V5/labs/Lab%20-%20Sub-queries%20and%20Nested%20SELECTs%20/instructional-labs.md.html?origin=www.coursera.org">Hands-on Lab : Sub-queries and Nested SELECT Statements</a>

*   <a href="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/Module%205/DB0201EN-Week3-1-3-SQLmagic.ipynb">Hands-on Tutorial: Accessing Databases with SQL magic</a>

*  <a href= "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/Module%205/DB0201EN-Week3-1-4-Analyzing.ipynb">Hands-on Lab: Analyzing a real World Data Set</a>

## Author(s)

<h4> Lakshmi Holla </h4>

## Other Contributors

<h4> Rav Ahuja </h4>

<!--
## Change log
| Date | Version | Changed by | Change Description |
|------|--------|--------|---------|
| 2024-07-10 | 1.1 |Anita Verma | Changed Version|
| 2021-07-09 | 0.2 |Lakshmi Holla | Changes made in magic sql|
| 2021-05-20 | 0.1 |Lakshmi Holla | Created Initial Version |
-->

## <h3 align="center"> © IBM Corporation 2021. All rights reserved. <h3/>